#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Linux" ];then
    release_id=$(grep "^ID=\".*\"$" /etc/os-release | cut -d"=" -f2 | tr -d "\"")
    pretty_name=$(grep "^PRETTY_NAME=\".*\"$" /etc/os-release | cut -d"=" -f2 | tr -d "\"")
    if [ "$release_id" = "opensuse-leap" ];then
	echo "Installing applications and build dependencies for ${pretty_name} ..."
        sudo zypper ref
        sudo zypper in vim tmux 
    fi
fi

if command -v vim >/dev/null 2>&1; then
  echo "Creating Backup folder for vim ..."
  mkdir .vim/backups
  echo "Bootstrapping vim plugins ..."
  vim '+PlugUpdate' '+qall'
fi
